apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../base

namespace: microservices

patches:
  - path: user-service-patch.yaml
    target:
      kind: Deployment
      name: user-service
  - path: order-service-patch.yaml
    target:
      kind: Deployment
      name: order-service

resources:
  - ingress.yaml
  - secrets.yaml

# Use locally built images (not registry)
images:
  - name: ghcr.io/pawanITC/user-service
    newName: user-service
    newTag: latest
  - name: ghcr.io/pawanITC/order-service
    newName: order-service
    newTag: latest
