# WARNING: These are LOCAL DEVELOPMENT ONLY placeholder secrets.
# For H2 (local), these values are not actually used by the application.
# NEVER commit real secrets to git. Use External Secrets Operator or Sealed Secrets in production.
---
apiVersion: v1
kind: Secret
metadata:
  name: user-service-secret
  namespace: microservices
type: Opaque
data:
  # base64("sa") = "c2E="  |  base64("") = ""
  DB_USERNAME: c2E=
  DB_PASSWORD: ""
---
apiVersion: v1
kind: Secret
metadata:
  name: order-service-secret
  namespace: microservices
type: Opaque
data:
  DB_USERNAME: c2E=
  DB_PASSWORD: ""
