apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../base

namespace: microservices

patches:
  - path: user-service-patch.yaml
    target:
      kind: Deployment
      name: user-service
  - path: order-service-patch.yaml
    target:
      kind: Deployment
      name: order-service

resources:
  - ingress.yaml
  - hpa.yaml

# Image tags will be set by CI/CD:
# kustomize edit set image ghcr.io/pawanITC/user-service=ghcr.io/pawanITC/user-service:$GIT_SHA
images:
  - name: ghcr.io/pawanITC/user-service
    newTag: latest
  - name: ghcr.io/pawanITC/order-service
    newTag: latest
