apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: microservices

commonLabels:
  app.kubernetes.io/part-of: microservices-platform

resources:
  - namespace.yaml
  - user-service/
  - order-service/
